postfix: "postprocessing"

seed: 42
precision: 16
accelerator: gpu
devices: 1
find_unused_parameters: False

dataset_root: /home/korotas/data/repro/inshop/
logs_root: /home/korotas/projects/repro/logs/
dataframe_name: df.csv
logs_folder: ${now:%Y-%m-%d_%H-%M-%S}_${postfix}

num_workers: 0
cache_size: 0
max_epochs: 1000
valid_period: 10

# CACHE EMBEDDINGS PRODUCED BY BASELINE FEATURE EXTRACTOR

embeddings_cache_train: /home/korotas/data/repro/inshop/emb_train.pt
embeddings_cache_val: /home/korotas/data/repro/inshop/emb_val.pt

extractor_weights: /home/korotas/data/repro/inshop/extractor_inshop.ckpt

extractor:
  name: vit
  args:
    normalise_features: True
    use_multi_scale: False
    weights: ${extractor_weights}
    arch: vits16

transforms_extraction:
  name: norm_resize_hypvit_albu
  args:
    im_size: 224
    crop_size: 224

# TRAIN POSTPROCESSOR

pairwise_model:
  name: concat_siamese
  args:
    mlp_hidden_dims: [192]
    extractor:
      name: vit
      args:
        normalise_features: False
        use_multi_scale: False
        weights: ${extractor_weights}
        arch: vits16

hard_pairs_mining: True

optimizer:
  name: adam
  args:
    lr: 2e-3

freeze_n_epochs: 3
scheduling:
  scheduler_interval: epoch
  scheduler_frequency: 1
  scheduler:
    name: multi_step
    args:
      gamma: 5e-3
      milestones:
        - ${freeze_n_epochs}

sampler:
  name: balance
  args:
    n_labels: 13
    n_instances: 4

transforms_train:
  name: augs_hypvit_albu
  args:
    im_size: 224
    min_scale: 0.8

# VALIDATE POSTPROCESSOR BY RE-RANKING TOP-N OUTPUTS

batch_size_inference: 128

postprocessor:
  name: pairwise_reranker
  args:
    top_n: 5
    pairwise_model: ${pairwise_model}
    num_workers: ${num_workers}
    batch_size: ${batch_size_inference}
    verbose: True
    use_fp16: True

metric_for_checkpointing: OVERALL/cmc/1
mode_for_checkpointing: max

log_images: False
metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1, 5]
  map_top_k: []
  fmr_vals: []
  pcf_variance: []
  precision_top_k: []
  return_only_overall_category: True
  visualize_only_overall_category: True

logger:
  name: clearml
  args:
    project_name: "OML Repro/inshop"
    task_name: "reproduction"
    offline_mode: False

tags:
  - postprocessing

hydra_dir: ${logs_root}/${logs_folder}/

hydra:
  run:
    dir: ${hydra_dir}
  searchpath:
    - pkg://oml.configs
  job:
    chdir: True
